# Generated by Django 5.1 on 2024-08-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='mobil_phone',
            new_name='mobile_phone',
        ),
    ]
