# Generated by Django 4.2.14 on 2024-09-01 08:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('slug', models.SlugField(blank=True, max_length=225, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.CharField(blank=True, choices=[('In_the_living', 'In_the_living'), ('Sale', 'Sale'), ('Rent', 'Rent')], default=None, max_length=225, null=True)),
                ('area', models.IntegerField(blank=True, default=0, null=True)),
                ('beds', models.IntegerField(blank=True, default=0, null=True)),
                ('baths', models.IntegerField(blank=True, default=0, null=True)),
                ('garages', models.IntegerField(blank=True, default=0, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
