# Generated by Django 5.1 on 2024-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('property', models.ManyToManyField(blank=True, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Amenites',
        ),
    ]
