# Generated by Django 5.1 on 2024-08-09 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_amenities_delete_amenites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='property',
        ),
        migrations.AddField(
            model_name='amenities',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
