# Generated by Django 5.1 on 2024-08-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_amenities_property_amenities_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='boths',
            new_name='baths',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='garage',
            new_name='garages',
        ),
    ]
